# Generated by Django 5.0 on 2025-11-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_class_created_by_alter_class_is_official'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatrequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='chatrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('sender', 'recipient'), name='unique_pending_request'),
        ),
    ]
