# Generated by Django 5.2.8 on 2025-12-09 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fix_last_login_nullable'),
        ('chat', '0003_chatroom_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('audio', 'Audio Call'), ('video', 'Video Call')], default='video', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ended', 'Ended'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Call duration in seconds', null=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to='accounts.studentprofile')),
                ('chat_room', models.ForeignKey(help_text='The chat room this call is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='chat.chatroom')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['caller', 'status'], name='chat_call_caller__9c00dd_idx'), models.Index(fields=['receiver', 'status'], name='chat_call_receive_b07ad5_idx'), models.Index(fields=['chat_room', '-initiated_at'], name='chat_call_chat_ro_b51b55_idx')],
            },
        ),
    ]
