# Generated by Django 5.2.8 on 2025-12-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='daily_room_id',
            field=models.CharField(blank=True, help_text='Daily.co room ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='daily_room_name',
            field=models.CharField(blank=True, help_text='Daily.co room name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='daily_room_url',
            field=models.URLField(blank=True, help_text='Daily.co room join URL', max_length=500, null=True),
        ),
    ]
