# Generated by Django 5.2.8 on 2025-12-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_call_daily_room_id_call_daily_room_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='daily_room_id',
        ),
        migrations.RemoveField(
            model_name='call',
            name='daily_room_name',
        ),
        migrations.RemoveField(
            model_name='call',
            name='daily_room_url',
        ),
    ]
