# Generated by Django 5.2.8 on 2025-12-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_call_daily_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='calendar_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether notification email was sent'),
        ),
        migrations.AddField(
            model_name='call',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When notification email was sent', null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='meet_link',
            field=models.URLField(blank=True, help_text='Google Meet link for the call', max_length=500, null=True),
        ),
    ]
