# Generated by Django 4.2.7 on 2025-11-05 21:05

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_mock_students(apps, schema_editor):
    """Create mock student data for testing"""
    User = apps.get_model('auth', 'User')
    StudentProfile = apps.get_model('accounts', 'StudentProfile')
    Class = apps.get_model('accounts', 'Class')
    StudentClass = apps.get_model('accounts', 'StudentClass')
    Location = apps.get_model('locations', 'Location')
    
    # Get or create classes
    classes_data = [
        {'code': 'CS2340', 'name': 'Objects and Design', 'department': 'Computer Science'},
        {'code': 'CS1332', 'name': 'Data Structures and Algorithms', 'department': 'Computer Science'},
        {'code': 'CS3510', 'name': 'Design and Analysis of Algorithms', 'department': 'Computer Science'},
        {'code': 'MATH1554', 'name': 'Linear Algebra', 'department': 'Mathematics'},
        {'code': 'PHYS2211', 'name': 'Introductory Physics I', 'department': 'Physics'},
        {'code': 'CS2110', 'name': 'Computer Organization and Programming', 'department': 'Computer Science'},
        {'code': 'CS3600', 'name': 'Introduction to Artificial Intelligence', 'department': 'Computer Science'},
        {'code': 'MATH2551', 'name': 'Multivariable Calculus', 'department': 'Mathematics'},
    ]
    
    classes = {}
    for class_data in classes_data:
        cls, created = Class.objects.get_or_create(
            code=class_data['code'],
            defaults={
                'name': class_data['name'],
                'department': class_data['department'],
                'is_official': True
            }
        )
        classes[class_data['code']] = cls
    
    # Get locations
    locations = list(Location.objects.all())
    if not locations:
        # Fallback if locations don't exist yet
        locations = [None]
    
    # Create mock students
    students_data = [
        {
            'username': 'asmith',
            'email': 'asmith@gatech.edu',
            'first_name': 'Alice',
            'last_name': 'Smith',
            'profile': {
                'name': 'Alice Smith',
                'year': 'junior',
                'location_privacy': False,
                'location_index': 0,  # Library - Price Gilbert
            },
            'classes': [
                ('CS2340', 'advanced'),
                ('CS1332', 'advanced'),
                ('MATH1554', 'intermediate'),
            ]
        },
        {
            'username': 'bjohnson',
            'email': 'bjohnson@gatech.edu',
            'first_name': 'Bob',
            'last_name': 'Johnson',
            'profile': {
                'name': 'Bob Johnson',
                'year': 'sophomore',
                'location_privacy': False,
                'location_index': 3,  # Klaus
            },
            'classes': [
                ('CS2340', 'intermediate'),
                ('CS1332', 'intermediate'),
                ('CS2110', 'advanced'),
            ]
        },
        {
            'username': 'clee',
            'email': 'clee@gatech.edu',
            'first_name': 'Charlie',
            'last_name': 'Lee',
            'profile': {
                'name': 'Charlie Lee',
                'year': 'senior',
                'location_privacy': True,  # Privacy enabled
                'location_index': 5,  # Instructional Center
            },
            'classes': [
                ('CS3510', 'advanced'),
                ('CS3600', 'intermediate'),
                ('CS2340', 'advanced'),
            ]
        },
        {
            'username': 'dpatel',
            'email': 'dpatel@gatech.edu',
            'first_name': 'Diana',
            'last_name': 'Patel',
            'profile': {
                'name': 'Diana Patel',
                'year': 'junior',
                'location_privacy': False,
                'location_index': 0,  # Library - Price Gilbert (same as Alice)
            },
            'classes': [
                ('CS2340', 'intermediate'),
                ('MATH1554', 'intermediate'),
                ('PHYS2211', 'beginner'),
            ]
        },
        {
            'username': 'ewilliams',
            'email': 'ewilliams@gatech.edu',
            'first_name': 'Ethan',
            'last_name': 'Williams',
            'profile': {
                'name': 'Ethan Williams',
                'year': 'freshman',
                'location_privacy': False,
                'location_index': 6,  # Clough Commons
            },
            'classes': [
                ('CS1332', 'beginner'),
                ('MATH1554', 'beginner'),
                ('PHYS2211', 'beginner'),
            ]
        },
        {
            'username': 'fgarcia',
            'email': 'fgarcia@gatech.edu',
            'first_name': 'Fiona',
            'last_name': 'Garcia',
            'profile': {
                'name': 'Fiona Garcia',
                'year': 'junior',
                'location_privacy': False,
                'location_index': 4,  # College of Computing
            },
            'classes': [
                ('CS2340', 'intermediate'),
                ('CS1332', 'advanced'),
                ('CS3600', 'beginner'),
            ]
        },
        {
            'username': 'gmartinez',
            'email': 'gmartinez@gatech.edu',
            'first_name': 'George',
            'last_name': 'Martinez',
            'profile': {
                'name': 'George Martinez',
                'year': 'senior',
                'location_privacy': False,
                'location_index': 3,  # Klaus
            },
            'classes': [
                ('CS3510', 'advanced'),
                ('CS2340', 'advanced'),
                ('MATH2551', 'intermediate'),
            ]
        },
        {
            'username': 'hrodriguez',
            'email': 'hrodriguez@gatech.edu',
            'first_name': 'Hannah',
            'last_name': 'Rodriguez',
            'profile': {
                'name': 'Hannah Rodriguez',
                'year': 'sophomore',
                'location_privacy': True,  # Privacy enabled
                'location_index': 1,  # Library - Crosland
            },
            'classes': [
                ('CS1332', 'intermediate'),
                ('MATH1554', 'intermediate'),
                ('CS2110', 'beginner'),
            ]
        },
        {
            'username': 'itaylor',
            'email': 'itaylor@gatech.edu',
            'first_name': 'Isaac',
            'last_name': 'Taylor',
            'profile': {
                'name': 'Isaac Taylor',
                'year': 'graduate',
                'location_privacy': False,
                'location_index': 4,  # College of Computing
            },
            'classes': [
                ('CS3600', 'advanced'),
                ('CS3510', 'advanced'),
                ('CS2340', 'advanced'),
            ]
        },
        {
            'username': 'janderson',
            'email': 'janderson@gatech.edu',
            'first_name': 'Julia',
            'last_name': 'Anderson',
            'profile': {
                'name': 'Julia Anderson',
                'year': 'junior',
                'location_privacy': False,
                'location_index': 0,  # Library - Price Gilbert (popular spot)
            },
            'classes': [
                ('CS2340', 'intermediate'),
                ('CS2110', 'intermediate'),
                ('MATH2551', 'beginner'),
            ]
        },
    ]
    
    for student_data in students_data:
        # Create user
        user, created = User.objects.get_or_create(
            username=student_data['username'],
            defaults={
                'email': student_data['email'],
                'first_name': student_data['first_name'],
                'last_name': student_data['last_name'],
                'password': make_password('password123'),  # Default password for testing
            }
        )
        
        if created:
            # Create profile
            profile_data = student_data['profile']
            location = None
            if locations[0] is not None and profile_data['location_index'] < len(locations):
                location = locations[profile_data['location_index']]
            
            profile = StudentProfile.objects.create(
                user=user,
                name=profile_data['name'],
                year=profile_data['year'],
                location_privacy=profile_data['location_privacy'],
                current_location=location,
                is_active=True
            )
            
            # Add classes with expertise levels
            for class_code, expertise in student_data['classes']:
                if class_code in classes:
                    StudentClass.objects.create(
                        student=profile,
                        course=classes[class_code],
                        expertise_level=expertise
                    )


def remove_mock_students(apps, schema_editor):
    """Remove mock students (reverse migration)"""
    User = apps.get_model('auth', 'User')
    
    mock_usernames = [
        'asmith', 'bjohnson', 'clee', 'dpatel', 'ewilliams',
        'fgarcia', 'gmartinez', 'hrodriguez', 'itaylor', 'janderson'
    ]
    
    User.objects.filter(username__in=mock_usernames).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_student_class_model"),
        ("locations", "0002_add_default_locations"),  # Need locations first
    ]

    operations = [
        migrations.RunPython(create_mock_students, remove_mock_students),
    ]
