# Generated by Django 5.0 on 2025-11-06 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_location_privacy_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this class (null if admin-created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='is_official',
            field=models.BooleanField(default=False, help_text='True if created by admin, False if user-created'),
        ),
    ]
