# Generated by Django 5.0 on 2025-11-06 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_class_created_by_alter_class_is_official'),
    ]

    operations = [
    ]
