# Generated by Django 4.2.7 on 2025-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_fix_last_login_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="current_latitude",
            field=models.FloatField(
                blank=True, help_text="Current latitude coordinate", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="current_longitude",
            field=models.FloatField(
                blank=True, help_text="Current longitude coordinate", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="location_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the GPS location was last updated",
                null=True,
            ),
        ),
    ]
