# Generated by Django 4.2.7 on 2025-12-10 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("study_sessions", "0003_add_course_to_studysession"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="room_number",
            field=models.CharField(
                blank=True, help_text="e.g. 304, Cubicle B", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="host",
            field=models.ForeignKey(
                help_text="User hosting this session",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="location",
            field=models.CharField(
                default="General Location",
                help_text="e.g. Library, Student Center",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
