# Generated by Django 4.2.7 on 2025-11-05 20:55

from django.db import migrations


def add_default_locations(apps, schema_editor):
    """Add default Georgia Tech campus locations"""
    Location = apps.get_model('locations', 'Location')
    
    default_locations = [
        {
            'name': 'Student Center',
            'building_name': 'Georgia Tech Student Center',
            'description': 'Main student center with study spaces and dining options',
        },
        {
            'name': 'Library - Price Gilbert',
            'building_name': 'Price Gilbert Library',
            'description': 'Main library with quiet study areas and group rooms',
        },
        {
            'name': 'Library - Crosland Tower',
            'building_name': 'Crosland Tower',
            'description': 'Library tower with collaborative study spaces',
        },
        {
            'name': 'Klaus Advanced Computing Building',
            'building_name': 'Klaus Advanced Computing Building',
            'description': 'Computing building with study lounges and computer labs',
        },
        {
            'name': 'College of Computing',
            'building_name': 'College of Computing',
            'description': 'CoC building with collaboration areas',
        },
        {
            'name': 'Instructional Center',
            'building_name': 'Instructional Center',
            'description': 'Large classroom building with study areas',
        },
        {
            'name': 'Clough Commons',
            'building_name': 'Clough Undergraduate Learning Commons',
            'description': 'Modern learning commons with innovative study spaces',
        },
        {
            'name': 'Manufacture Related Disciplines Complex (MRDC)',
            'building_name': 'MRDC',
            'description': 'Engineering building with study spaces',
        },
    ]
    
    for location_data in default_locations:
        Location.objects.get_or_create(
            name=location_data['name'],
            defaults={
                'building_name': location_data['building_name'],
                'description': location_data['description'],
                'is_active': True,
            }
        )


def remove_default_locations(apps, schema_editor):
    """Remove default locations (reverse migration)"""
    Location = apps.get_model('locations', 'Location')
    
    default_location_names = [
        'Student Center',
        'Library - Price Gilbert',
        'Library - Crosland Tower',
        'Klaus Advanced Computing Building',
        'College of Computing',
        'Instructional Center',
        'Clough Commons',
        'Manufacture Related Disciplines Complex (MRDC)',
    ]
    
    Location.objects.filter(name__in=default_location_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_default_locations, remove_default_locations),
    ]
