# Generated by Django 4.2.7 on 2025-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_add_default_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="address",
            field=models.CharField(
                blank=True, help_text="Full address from geocoding", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Latitude coordinate", null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Longitude coordinate", null=True
            ),
        ),
    ]
